name: Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TPL_FIREBASE_AUTH: ${{ github.workspace }}/firebase-key.json
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set up environment variables
        run: |-
          echo "${{ secrets.FIREBASE_KEY_JSON_BASE64 }}" | base64 --decode > firebase-key.json
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: pytest -s -p no:warnings --cov=src --cov-fail-under=80